// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3d7KFhNGCqd8nhN1SLpAE_HG6pROqlnE',
    appId: '1:9251461554:web:e6f4311d66991da0fb2cab',
    messagingSenderId: '9251461554',
    projectId: 'chat-board-7722a',
    authDomain: 'chat-board-7722a.firebaseapp.com',
    storageBucket: 'chat-board-7722a.firebasestorage.app',
    measurementId: 'G-Y1GHH0WGLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI91SvejtEY6Mr5dS_T6XTSvnly9bzLGo',
    appId: '1:9251461554:android:7771789eb33298b4fb2cab',
    messagingSenderId: '9251461554',
    projectId: 'chat-board-7722a',
    storageBucket: 'chat-board-7722a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ajGMVqV7bo7eQIRGUra8OF6wjnomCsw',
    appId: '1:9251461554:ios:bebf254a1ef61d06fb2cab',
    messagingSenderId: '9251461554',
    projectId: 'chat-board-7722a',
    storageBucket: 'chat-board-7722a.firebasestorage.app',
    iosBundleId: 'com.example.chatboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ajGMVqV7bo7eQIRGUra8OF6wjnomCsw',
    appId: '1:9251461554:ios:bebf254a1ef61d06fb2cab',
    messagingSenderId: '9251461554',
    projectId: 'chat-board-7722a',
    storageBucket: 'chat-board-7722a.firebasestorage.app',
    iosBundleId: 'com.example.chatboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3d7KFhNGCqd8nhN1SLpAE_HG6pROqlnE',
    appId: '1:9251461554:web:9b30728aa0cdf5e3fb2cab',
    messagingSenderId: '9251461554',
    projectId: 'chat-board-7722a',
    authDomain: 'chat-board-7722a.firebaseapp.com',
    storageBucket: 'chat-board-7722a.firebasestorage.app',
    measurementId: 'G-MRLM4DB7G3',
  );
}
